version: '3.8'


services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-local-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD='p@ss_root@1234'
      - MYSQL_DATABASE=sa
      - MYSQL_USER=db_app
      - MYSQL_PASSWORD='senhaforte1234'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: