name: CI/CD - Build, Terraform and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1
  APP_NAME: my-java-app
  GAR_REPO: api-repo
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }} # Passa o segredo para o Terraform

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download Maven dependencies
        run: mvn dependency:go-offline

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.APP_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="gcp_project_id=${{ env.GCP_PROJECT_ID }}" \
            -var="app_name=${{ env.APP_NAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}"

      # <<< A CORREÇÃO FINAL ESTÁ NESTE PASSO ABAIXO >>>
      - name: Deploy to Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.APP_NAME }}
          region: ${{ env.GCP_REGION }}
          image: ${{ steps.build-image.outputs.digest }}

          # As variáveis de ambiente para a aplicação rodando no Cloud Run
          env_vars: |-
            DB_USER=root
            DB_NAME=
            # A URL do banco (DB_HOST) será injetada automaticamente pela seção 'database' abaixo

          # A seção 'database' deve estar aqui, no mesmo nível de 'service' e 'image'
          database:
            instance: ${{ env.APP_NAME }}-mysql-db
            secrets:
              # Mapeia o segredo do GitHub para a variável de ambiente DB_PASSWORD
              # que a aplicação irá usar para se conectar
              - name: DB_PASSWORD
                value: ${{ secrets.DB_PASSWORD }}

      - name: Show Output
        run: "echo 'Deploy finalizado! Acesse sua API em: ${{ steps.deploy.outputs.url }}'"